config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post '/search' => 'home#search'
  get '/test' => 'home#test'
  # post '/romance' => 'home#romance'
  # post '/magic' => 'home#magic'
  # post '/mystery' => 'home#mystery'
  # post '/comedy' => 'home#comedy'
  # post '/scifi' => 'home#scifi'
  # post '/action' => 'home#action'
  # post '/adventure' => 'home#adventure'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/anime.rb
class Anime < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  AUTH = '936dd662054f71d5c137'
  @@anime = Array.new
  
  def index
  end

 def search
  @@anime = []
  case params[:data]
  when "Romance"
    getMovie("Romance")
  when "Magic"
    getMovie("Magic", "Thriller")
  when "Mystery"
    getMovie("Mystery")
  when "Comedy"
    getMovie("Comedy")
  when "Sci-Fi"
    getMovie("Sci-Fi")
  when "Action"
    getMovie("Action")
  when "Adventure"
    getMovie("Adventure")
  else

  end
  
  @token = @@anime[0].token
  @ename = @@anime[0].e_title
  @jname = @@anime[0].j_title
  @youtube = @@anime[0].Youtube
  @dt = sendTrailer(@token, @youtube)
 
 end

 def test
  
  name = "sword-art-online-ii"
  @response = HTTParty.get("http://hummingbird.me/api/v2/anime/#{name}.json", headers:{'X-Client-Id'=> AUTH})
  render :test
 
 end

 def getMovie(*args)
    @all = Anime.count
    @@anime = Anime.where(["genre1 IN (:args) OR genre2 IN (:args) OR genre3 IN (:args) OR genre4 IN (:args) OR genre5 IN (:args)", {args: args}]).shuffle
  end

  def sendTrailer(token, youtube)
    @dt = []
    @response = HTTParty.get("http://hummingbird.me/api/v2/anime/#{token}.json", headers:{'X-Client-Id'=> AUTH})
    if(youtube == "" ||youtube == nil) then
      @dt[0] = "https://www.youtube.com/embed/#{@response.parsed_response['anime']['youtube_video_id']}?autoplay=1&amp;&showinfo=0&amp;rel=0&amp;controls=0&amp;showinfo=0"
     else
      @dt[0] = "https://www.youtube.com/embed/#{youtube}?autoplay=1&amp;&showinfo=0&amp;rel=0&amp;controls=0&amp;showinfo=0"
     end
      @dt[1] = @response.parsed_response['anime']['synopsis']
      p @dt[1]
     return @dt
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="title">
	-Shouni
</div>
<div class="video"><%= video_tag "anime_comp1.mp4", autoplay:true, height: "100%", width: "100%", loop: true%>
</div>

<div class="bar">
	<div class="faces">
		<%= link_to image_tag("romance.png"), search_path(data: "Romance"), class:"icon", title:"Romance", method: :post %>
		<%= link_to image_tag("magic_fantasy.png"), search_path(data: "Magic"), class:"icon", title:"Magic & Fantasy", method: :post %>
		<%= link_to image_tag("mystery.png"), search_path(data: "Mystery"), class:"icon", title:"Mystery", method: :post %>
		<%= link_to image_tag("comedy.png"), search_path(data: "Comedy"), class:"icon", title:"Comedy", method: :post %>
		<%= link_to image_tag("scifi.png"), search_path(data: "Sci-Fi"), class:"icon", title:"Sci-Fi",method: :post %>
		<%= link_to image_tag("thriller_action.png"), search_path(data: "Action"), class:"icon", title:"Thriller & Action", method: :post %>
		<%= link_to image_tag("adventure.png"), search_path(data: "Adventure"), class:"icon", title:"Adventure", method: :post %>
	</div>
</div>
 
<div class="test_link"><%= link_to "For testing purposes", test_path %></div>
 

app/views/home/search.html.erb
<div class="trigger">
	
	<div class="title" id="eng">
		
		<%= @ename %> <br>
		<%= @jname %>
	
	</div>

</div>

<div class="side">

	<div class="sidebar">
		
		<div class="logo">
			
			<%= link_to "-Shouni", root_path, :style=>'color:black;'%> 
		
		</div>
	
	</div>  

</div>

<%= link_to search_path(data: params[:data]), method: :post do %>
	<div class="forward"></div>
<% end %>

<iframe width="100%" height="120%" style="undefined" z-index="-10" bgcolor="#000000" quality="true" scale="noscale" allowfullscreen="true" wmode="transparent" menu="false" src="<%= @dt[0] %>"></iframe>

<div class="syn_hid" id="synp"><%= @dt[1] %></div>

app/views/home/test.html.erb
<%= @response.parsed_response %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>~Shouni</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    </head>

    <body  class="<%= controller_name %> <%= action_name %>">
    <%= yield %>
    </body>
</html>